[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_MAINNET_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_BASE_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_ARBITRUM_API_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

